# Generated by Django 4.2 on 2023-06-05 17:34

import api.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('cv', models.FileField(blank=True, null=True, upload_to='', validators=[api.validators.FileValidator(content_types=('application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'), max_size=10240000)], verbose_name='CV')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='', validators=[api.validators.FileValidator(content_types=('application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'), max_size=10240000)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('not_applied', 'Not applied'), ('applied', 'Applied'), ('phone_screening', 'Phone screening'), ('interview', 'Interview'), ('technical_interview', 'Technical interview'), ('rejected', 'Rejected'), ('offer', 'Offer')], default='not_applied', max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contacts', models.CharField(blank=True, help_text='Provide contacts of the person of reference', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any notes', null=True)),
                ('offered_salary', models.PositiveIntegerField(blank=True, help_text='Your offered salary', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.application')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
