# Generated by Django 4.2 on 2023-06-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationphase',
            name='name',
            field=models.CharField(choices=[('not_applied', 'Not applied'), ('applied', 'Applied'), ('phone_screening', 'Phone screening'), ('interview', 'Interview'), ('technical_interview', 'Technical interview'), ('rejected', 'Rejected'), ('offer', 'Offer')], max_length=30),
        ),
    ]
