# Generated by Django 4.2 on 2023-06-27 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_applicationphase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationphase',
            name='offered_salary',
        ),
        migrations.AddField(
            model_name='application',
            name='offered_salary',
            field=models.PositiveIntegerField(blank=True, help_text='Your offered salary', null=True),
        ),
        migrations.AddField(
            model_name='applicationphase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
