# Generated by Django 4.2 on 2023-06-27 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_applicationphase_offered_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationphase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
