# Generated by Django 4.2 on 2023-06-27 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_applicationphase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationphase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
