# Generated by Django 4.2 on 2023-06-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_applicationphase_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationphase',
            options={'ordering': ['-date', '-created']},
        ),
        migrations.AlterField(
            model_name='applicationphase',
            name='date',
            field=models.DateField(blank=True, help_text='The date of the event', null=True),
        ),
    ]
