# Generated by Django 4.2 on 2023-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_applicationphase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationphase',
            name='name',
            field=models.CharField(choices=[('applied', 'Applied'), ('phone_screening', 'Phone screening'), ('interview', 'Interview'), ('technical_interview', 'Technical interview'), ('rejected', 'Rejected'), ('offer', 'Offer')], max_length=30),
        ),
    ]
