# Generated by Django 4.2 on 2023-06-29 13:05

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_applicationphase_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationphase',
            options={'ordering': [models.OrderBy(django.db.models.functions.comparison.Coalesce(models.F('date'), models.F('created')), descending=True)]},
        ),
        migrations.AddField(
            model_name='application',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
