# Generated by Django 4.2 on 2023-09-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_applicationphase_options_application_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
