# Generated by Django 4.2 on 2024-01-30 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import application_tracker.general.validators.file_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'default_cv',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='',
                        validators=[
                            application_tracker.general.validators.file_validator.FileValidator(
                                content_types=(
                                    'application/pdf', 'application/msword',
                                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
                                ),
                                max_size=10240000
                            )
                        ],
                        verbose_name='Default CV'
                    )
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='preferences',
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
        ),
    ]
