- name: Creating systemd Socket for gunicorn
  copy:
    src: gunicorn.socket
    dest: /etc/systemd/system/gunicorn.socket
    owner: root
    group: root
    mode: 0644

- name: Creating systemd Service for gunicorn
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    owner: root
    group: root
    mode: 0644

- name: Start gunicorn socket and service
  script: gunicorn.sh

