# Generated by Django 4.2 on 2024-01-29 16:00

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models

import application_tracker.general.validators.file_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                (
                    'cv',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='',
                        validators=[
                            application_tracker.general.validators.file_validator.FileValidator(
                                content_types=(
                                    'application/pdf', 'application/msword',
                                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
                                ),
                                max_size=10240000
                            )
                        ],
                        verbose_name='CV'
                    )
                ),
                (
                    'cover_letter',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='',
                        validators=[
                            application_tracker.general.validators.file_validator.FileValidator(
                                content_types=(
                                    'application/pdf', 'application/msword',
                                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
                                ),
                                max_size=10240000
                            )
                        ]
                    )
                ),
                (
                    'offered_salary',
                    models.PositiveIntegerField(blank=True, help_text='Your offered salary', null=True)
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='applications',
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'name',
                    models.CharField(
                        choices=[('applied', 'Applied'), ('phone_screening', 'Phone screening'),
                                 ('interview', 'Interview'), ('technical_interview', 'Technical interview'),
                                 ('rejected', 'Rejected'), ('offer', 'Offer')],
                        max_length=30
                    )
                ),
                ('date', models.DateField(blank=True, help_text='The date of the event', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'contacts',
                    models.CharField(
                        blank=True, help_text='Provide contacts of the person of reference', max_length=255, null=True
                    )
                ),
                ('notes', models.TextField(blank=True, help_text='Any notes', null=True)),
                (
                    'application',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='phases',
                        to='applications.application'
                    )
                ),
            ],
            options={
                'ordering': [
                    models.OrderBy(
                        django.db.models.functions.comparison.Coalesce(models.F('date'), models.F('created')),
                        descending=True
                    )
                ],
            },
        ),
    ]
