name: Continuous Integration Staging

on:
  push:
    branches:
      - backend-refactor

concurrency:
  group: dev
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END
      - name: Create .env files
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          REACT_APP_ENV_FILE: ${{ secrets.REACT_APP_ENV_FILE }}
        run: |
          ssh target "cd /opt/qa/application-tracker/ && echo $ENV_FILE > .env && echo $REACT_APP_ENV_FILE > frontend/.env"
      - name: Run deploy
        run: |
          ssh target "cd /opt/qa/application-tracker/ && git pull && make run-production
